CREATE TABLE IF NOT EXISTS Users (
id VARCHAR(60) PRIMARY KEY,
username VARCHAR(150) NOT NULL,
password VARCHAR(15) NOT NULL
);

CREATE TABLE IF NOT EXISTS Sales (
id VARCHAR(60) PRIMARY KEY,
costumerId VARCHAR(60) NOT NULL,
price FLOAT NOT NULL,
tax FLOAT NOT NULL,
saleDate DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS Store (
id VARCHAR(60) PRIMARY KEY,
name VARCHAR(150) NOT NULL,
address VARCHAR(150) NOT NULL,
number INT NOT NULL,
neighbor VARCHAR(150) NOT NULL,
state VARCHAR(10),
city VARCHAR(60),
country VARCHAR(60)
);

CREATE TABLE IF NOT EXISTS Customer_Types (
id VARCHAR(60) PRIMARY KEY,
description VARCHAR(60)
);

CREATE TABLE IF NOT EXISTS Costumers (
id VARCHAR(60) PRIMARY KEY,
name VARCHAR(150) NOT NULL,
age INT NOT NULL,
costumerType VARCHAR(60) NOT NULL,
FOREIGN KEY (costumerType) REFERENCES Customer_Types(id)
);

CREATE TABLE IF NOT EXISTS Customer_Stores (
  id VARCHAR(60) PRIMARY KEY,
  customerId VARCHAR(60) NOT NULL,
  storeId VARCHAR(60) NOT NULL,
  changeDate DATE,
  FOREIGN KEY (customerId) REFERENCES Costumers(id),
  FOREIGN KEY (storeId) REFERENCES Store(id)
);

